### ISSUE TITLE
A few more params

### ISSUE THREAD

**Issue by rbucker** [alexandre-normand/safekeeper#1]
This seems to be a better alternative than the -L param in the build command. What about adding the git version, build version and date? I suppose I could precook the values I'm thinking about into ENV variables but what fun would that be?

**Comment by alexandre-normand** [comment]
I'm not opposed to adding more tracing info. Do you want to try and tackle this?

**Comment by rbucker** [comment]
It would be easy enough to do, however, I'm wrestling with the idea at the moment. (a) how secure is it really if the build pipeline needs to keep this information in the environment. At some point it needs to be stores so that it can be restored (b) Putting the credentials in the code makes the attack vector the program and not the environment. The application is going to leave echo of itself as it's backed up, tested in staging and so on. (c) with the discovery services associated with tools like etcd this sort of thing might be delayed until actual runtime instead of at-rest.

**Comment by alexandre-normand** [comment]
I understand your concerns. This isn't meant to be the most secure solution ever. It just happens to be one that's compatible with the constraints of Google App Engine (and maybe others). I'm closing for the moment but if anyone wants to work on this, I'm okay to reopen.
